/* Owner changes are versioned. Generated code never replaces the live app. */
const customizeSection=document.createElement('section');customizeSection.className='group compact-section';
async function editMemoryDetail(m){try{const d=await api('/api/memories/'+m.id+'/versions');showDetail('Ingatan','<label>Isi ingatan<textarea class="inp" id="memoryEdit" rows="6" maxlength="12000">'+esc(m.text)+'</textarea></label><button class="btn pri" id="saveMemoryEdit">Simpan revisi</button><details><summary>Riwayat versi</summary>'+d.versions.map(v=>'<article><pre class="detail-text">'+esc(v.content)+'</pre><button class="btn sm" data-memory-version="'+v.id+'">Pulihkan</button></article>').join('')+'</details>');$('#saveMemoryEdit').onclick=async()=>{try{await api('/api/memories/'+m.id+'/edit',{method:'POST',body:{text:$('#memoryEdit').value}});$('#recordDetail').close();await loadMem();toast('Ingatan direvisi.')}catch(e){sayError(e)}};$$('[data-memory-version]').forEach(b=>b.onclick=async()=>{await api('/api/memories/'+m.id+'/edit',{method:'POST',body:{action:'restore',version:Number(b.dataset.memoryVersion)}});$('#recordDetail').close();await loadMem()})}catch(e){sayError(e)}}
customizeSection.innerHTML='<h4 class="group-h">Instruksi & perbaikan aplikasi</h4><div class="group-b"><p class="hint">Baca instruksi agen, edit dengan riwayat versi, atau minta AI membuat draft perubahan kode. Aplikasi aktif tetap berjalan.</p><div class="row"><button class="btn" type="button" id="openHarness">Lihat & edit harness</button><button class="btn" type="button" id="openRepair">Minta perbaikan</button></div></div>';
$('#harnessMode').closest('section').after(customizeSection);
$('#openHarness').onclick=async()=>{try{const d=await api('/api/customization?bot='+encodeURIComponent(S.bot?.id||'asisten'));showDetail('Instruksi agen','<p class="hint">'+esc(d.guard)+'</p><label>Instruksi tambahan<textarea class="inp" rows="6" maxlength="12000" id="customHarness">'+esc(d.custom)+'</textarea></label><div class="row"><button class="btn pri" id="saveHarness">Simpan</button><button class="btn" id="defaultHarness">Kembali bawaan</button></div><details><summary>Prompt aktif · izin alat · cakupan ingatan</summary><pre class="detail-text">'+esc(d.effective_prompt)+'\n\nAlat: '+esc(d.tools.join(', '))+'\nIngatan: '+esc(d.memory_scope)+'</pre></details><details><summary>Riwayat instruksi</summary>'+d.versions.map(v=>'<article><small>'+esc(new Date(v.created_at*1000).toLocaleString())+'</small><pre class="detail-text">'+esc(v.content||'(Bawaan)')+'</pre><button class="btn sm" data-harness-version="'+v.id+'">Pulihkan</button></article>').join('')+'</details>');
 $('#saveHarness').onclick=async()=>{try{await api('/api/customization',{method:'POST',body:{action:'save',text:$('#customHarness').value}});$('#recordDetail').close();toast('Instruksi disimpan. Berlaku untuk pesan berikutnya.')}catch(e){sayError(e)}};
 $('#defaultHarness').onclick=async()=>{if(!await uiConfirm('Pulihkan instruksi bawaan? Instruksi sekarang disimpan sebagai versi, skill dan ingatan tetap ada.'))return;await api('/api/customization',{method:'POST',body:{action:'default'}});$('#recordDetail').close();toast('Instruksi kembali bawaan.')};
 $$('[data-harness-version]').forEach(b=>b.onclick=async()=>{await api('/api/customization',{method:'POST',body:{action:'restore',version:Number(b.dataset.harnessVersion)}});$('#recordDetail').close();toast('Versi dipulihkan.')});
 }catch(e){sayError(e)}};
let repairTimer;
$('#openRepair').onclick=async()=>{try{const d=await api('/api/customization');showDetail('Perbaikan aplikasi','<p class="hint">AI membuat salinan perubahan. Draft tidak dijalankan atau dipasang. Setelah review, uji branch di GitHub Zwart04/agenmini dan pasang release yang lulus. Akun, penjaga, data dan runtime tidak dapat diedit.</p><label>Tujuan<textarea class="inp" rows="3" id="repairPrompt" maxlength="6000" placeholder="Perbaiki tampilan kartu model di mobile…"></textarea></label><label>Bot<select class="inp" id="repairBot">'+S.bots.map(b=>'<option value="'+esc(b.id)+'">'+esc(b.name)+'</option>').join('')+'</select></label><details><summary>Pilih berkas yang relevan (maksimal 6)</summary><div class="checks">'+d.files.map(f=>'<label><input type="checkbox" name="repairFile" value="'+esc(f)+'">'+esc(f)+'</label>').join('')+'</div></details><button class="btn pri" id="startRepair">Buat draft dengan AI</button><div id="repairRows"></div>');
 $('#startRepair').onclick=async()=>{const b=$('#startRepair');b.disabled=true;try{await api('/api/repairs',{method:'POST',body:{prompt:$('#repairPrompt').value,bot:$('#repairBot').value,files:$$('[name=repairFile]:checked').map(x=>x.value)}});await refreshRepairs()}catch(e){sayError(e)}finally{b.disabled=false}};
 await refreshRepairs();clearInterval(repairTimer);repairTimer=setInterval(()=>{if($('#recordDetail').open&&$('#repairRows')&&!document.hidden)refreshRepairs().catch(sayError);else if(!$('#repairRows'))clearInterval(repairTimer)},3000);
 }catch(e){sayError(e)}};
async function refreshRepairs(){const d=await api('/api/repairs');if(!$('#repairRows'))return;$('#repairRows').innerHTML=d.repairs.map(r=>'<article class="activity-row"><div class="grow"><b>'+esc(r.prompt.slice(0,100))+'</b><p class="hint">'+(['queued','generating'].includes(r.status)?'<span class="runtime-spinner" aria-hidden="true"></span> ':'')+esc({queued:'Menunggu',generating:'AI menyiapkan perubahan',draft:'Draft selesai · belum diuji integrasi',failed:'Gagal',interrupted:'Dihentikan'}[r.status]||r.status)+'</p><p class="hint">'+esc(r.error||r.result.summary||'')+'</p>'+(r.status==='draft'?'<button class="btn sm" data-repair-diff="'+r.id+'">Lihat diff</button> <a class="btn sm" href="/api/repairs/'+r.id+'/download">Unduh draft ZIP</a>':'')+(['queued','generating'].includes(r.status)?'<button class="btn sm" data-repair-cancel="'+r.id+'">Batalkan</button>':'')+'</div></article>').join('')||'<p class="hint">Belum ada draft. Berkas asli tetap utuh jika model gagal.</p>';
 $$('[data-repair-diff]').forEach(b=>b.onclick=async()=>{const r=await api('/api/repairs/'+b.dataset.repairDiff);showDetail('Review perubahan','<p class="hint">'+esc(r.result.checks)+'</p><pre class="detail-text">'+esc(r.result.files.map(f=>f.diff).join('\n'))+'</pre><p class="hint">'+esc(r.result.deployment)+'</p>')});
 $$('[data-repair-cancel]').forEach(b=>b.onclick=async()=>{await api('/api/repairs/'+b.dataset.repairCancel+'/cancel',{method:'POST',body:{}});await refreshRepairs()});}
