async function loadLearning(){
 const d=await api('/api/learning');
 $('#learningInfo').textContent=d.training+' '+d.versions+' revisi skill tersimpan. Kandidat menunggu tinjauan, bukan bukti keberhasilan seluruh tugas.';
 $('#learningCandidates').innerHTML=d.candidates.map(c=>`<article class="activity-row"><div class="grow"><b>${esc(c.name)}</b><span class="pill">${esc({pending:'Perlu tinjauan',accepted:'Diterima',rejected:'Ditolak',corrected:'Dikoreksi'}[c.status]||c.status)}</span><p class="hint">${esc(c.bot)} · pesan #${c.message_id}</p><button class="btn sm" data-learning="${c.id}">Bukti & langkah</button></div></article>`).join('')||'<p class="hint">Belum ada pekerjaan dengan hasil alat yang memenuhi syarat. Sapaan tidak dibuat menjadi skill.</p>';
 $$('[data-learning]').forEach(b=>b.onclick=()=>{const c=d.candidates.find(c=>c.id===Number(b.dataset.learning));showDetail(c.name,'<h4>Bukti alat</h4><pre class="detail-text">'+esc(c.evidence)+'</pre><label>Langkah yang bisa digunakan ulang<textarea id="learningSteps" class="inp" rows="8" maxlength="1500">'+esc(c.steps)+'</textarea></label>'+(c.status==='pending'?'<div class="row"><button class="btn" id="refineLearning">Perbaiki dengan AI</button><button class="btn pri" id="acceptLearning">Terima & aktifkan</button><button class="btn" id="rejectLearning">Tolak</button></div>':'<p class="hint">'+esc(c.status)+'</p>'));
  for(const [id,action] of [['refineLearning','refine'],['acceptLearning','accept'],['rejectLearning','reject']]){const btn=$('#'+id);if(btn)btn.onclick=async()=>{try{await api('/api/learning/'+c.id,{method:'POST',body:{action,steps:$('#learningSteps').value}});$('#recordDetail').close();await loadSkills()}catch(e){sayError(e)}}}
 });
}
$('#refreshLearning').onclick=()=>loadLearning().catch(sayError);
$('#trainingExport').onclick=async()=>{if(!await uiConfirm('Ekspor pesan privat yang dinilai Sesuai ke komputer ini? Tinjau data sebelum dipakai untuk training. Tidak dikirim ke provider.'))return;try{const r=await fetch('/api/training/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({include_private_conversations:true})});if(!r.ok)throw Error((await r.json()).error);const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='agenmini-confirmed.jsonl';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}catch(e){sayError(e)}};
