/* Local 9router artwork; no external logo requests or additional dashboard. */
let providerCardsFingerprint='';
function renderProviderCards(data){
 document.querySelectorAll('a[href="/apps/router/dashboard"]').forEach(a=>a.classList.toggle('hidden',data.engine==='go'));
 let panel=document.getElementById('providerPicker');
 if(!panel){panel=document.createElement('section');panel.id='providerPicker';panel.className='provider-picker';document.getElementById('routerPanel').prepend(panel)}
 const rows=data.provider_catalog||[];
 if(!document.getElementById('providerExtra')){
  const extra=document.createElement('details');extra.id='providerExtra';extra.className='compact-section';extra.innerHTML='<summary>Konfigurasi khusus (opsional)</summary><label>Machine ID Cursor<input class="inp" id="providerMachine" autocomplete="off"></label><label>Konfigurasi endpoint / proyek (JSON)<textarea class="inp" id="providerConfig" rows="3" placeholder="{}"></textarea></label><p class="hint">Misalnya baseUrl, projectId atau deployment dari provider Anda. Jangan isi jika tidak diperlukan.</p>';
  document.getElementById('providerForm').insertBefore(extra,document.getElementById('providerForm').querySelector(':scope > button'));
 }
 const apiSelect=document.getElementById('apiProvider');apiSelect.onchange=()=>{const meta=rows.find(p=>p.id===apiSelect.value)||{},key=document.getElementById('providerKey');key.required=!meta.noAuth;key.disabled=!!meta.noAuth;document.querySelector('label[for="providerKey"]').textContent=meta.authHint||(meta.id==='cursor'?'Access token Cursor':meta.noAuth?'Tidak perlu key':'API key provider')};apiSelect.onchange();
 const fingerprint=JSON.stringify(rows);if(fingerprint===providerCardsFingerprint)return;providerCardsFingerprint=fingerprint;
 panel.innerHTML='<h3>Hubungkan AI</h3><p class="hint">Pilih provider, lalu login atau masukkan API key. Model muncul setelah tersambung.</p><input class="inp" type="search" id="providerSearch" placeholder="Cari provider…" aria-label="Cari provider"><div class="provider-grid"></div>';
 const draw=()=>{const q=document.getElementById('providerSearch').value.toLowerCase(),grid=panel.querySelector('.provider-grid');grid.replaceChildren();for(const row of rows.filter(p=>p.name.toLowerCase().includes(q)||p.id.includes(q))){const b=document.createElement('button');b.type='button';b.className='provider-card';const name=document.createElement('span');name.textContent=row.name;if(row.logo){const img=document.createElement('img');img.src=row.logo;img.alt='';img.width=28;img.height=28;img.loading='lazy';b.append(img)}b.append(name);const methods=[...(data.api_providers.includes(row.id)?[row.noAuth?'Tanpa login':row.authType==='cookie'?'Cookie':row.id==='cursor'?'Impor token':'API key']:[]),...((data.device_providers.includes(row.id)||data.code_providers.includes(row.id))?['Login']:[])];const hint=document.createElement('small');hint.textContent=methods.join(' · ');b.append(hint);b.onclick=async()=>{if(row.noAuth){b.disabled=true;try{await api('/api/router/provider',{method:'POST',body:{provider:row.id,name:row.name}});toast('Sumber gratis diaktifkan; pilih model lalu uji koneksi.');await loadAI()}catch(e){sayError(e)}finally{b.disabled=false}return}if(!methods.length){toast('Provider ini memerlukan impor token atau konfigurasi khusus upstream.');return}const id=methods.includes('Login')?'oauthProvider':'apiProvider',select=document.getElementById(id);select.value=row.id;select.dispatchEvent(new Event('change',{bubbles:true}));refreshDesignControls();select.closest('form,.control-form').scrollIntoView({behavior:'smooth',block:'center'});document.getElementById(id==='oauthProvider'?'oauthStart':'providerKey').focus()};grid.append(b)}};
 panel.querySelector('input').oninput=draw;draw();
}
