/* Explicit presets and host setup; no extra client dependencies. */
const setupExtra=document.createElement('section');setupExtra.className='compact-section';
setupExtra.innerHTML=`<label class="toggle-row"><input type="checkbox" id="setupBotTemplates">Tambahkan template tim bot</label><p class="hint">Orchestrator selalu menjadi bot awal. Template menambahkan spesialis; skill, ingatan dan harness mengikuti pilihan terpisah di atas.</p><label>Sandi web baru (opsional)<input class="inp" id="setupPassword" type="password" autocomplete="new-password" minlength="8" maxlength="200"></label><label>Ulangi sandi<input class="inp" id="setupPasswordConfirm" type="password" autocomplete="new-password"></label><p class="hint">Kosongkan untuk mempertahankan sandi pemasangan. Mengganti sandi akan meminta login ulang.</p><label id="setupSwapRow" class="hidden">Swap VPS<select class="inp" id="setupSwap"><option value="0">Tidak menambah swap</option><option value="2">Tambah 2 GB</option><option value="4">Tambah 4 GB</option><option value="8">Tambah 8 GB</option></select></label><p class="hint" id="setupSwapHint"></p>`;
document.getElementById('setupDone').before(setupExtra);
document.getElementById('setupProfile').addEventListener('change',()=>{document.getElementById('setupBotTemplates').checked=document.getElementById('setupProfile').value==='template'});
document.getElementById('setupDone').onclick=async()=>{
 const password=document.getElementById('setupPassword').value;if(password!==document.getElementById('setupPasswordConfirm').value)return toast('Kedua sandi harus sama.');
 try{const result=await api('/api/setup',{method:'POST',body:{profile:$('#setupProfile').value,harness:$('#setupHarness').value,full_access:$('#setupFullAccess').checked,bot_templates:$('#setupBotTemplates').checked,password,swap_gb:Number($('#setupSwap').value)}});$('#setupPassword').value='';$('#setupPasswordConfirm').value='';$('#setupGuide').classList.add('hidden');if(password){location.reload();return}await refreshBots();go('chat');toast(result.mcp_errors?.length?'Setup disimpan; periksa koneksi MCP.':'Setup disimpan. Orchestrator siap setelah model terhubung.')}catch(e){sayError(e)}
};
const templateDescriptions={asisten:'Bantuan umum, berkas dan pengingat.',riset:'Riset web dan ringkasan dengan sumber.',pengingat:'Pengingat dan jadwal rutin.',teknisi:'Coding, perintah dan pemeriksaan server.',trading:'Analisis pasar dan simulasi, tanpa transaksi.',sosmed:'Strategi konten dan kalender publikasi.',copywriter:'Caption, naskah dan draf email.',desainer:'Desain antarmuka, brief dan kode.',reviewer:'Pemeriksaan hasil, sumber dan angka.'};
const templatesButton=document.createElement('button');templatesButton.type='button';templatesButton.className='btn';templatesButton.id='chooseBotTemplates';templatesButton.textContent='Template bot';document.getElementById('addBot').before(templatesButton);
const botTemplates=document.createElement('div');botTemplates.className='modal hidden';botTemplates.id='botTemplatesModal';
botTemplates.setAttribute('role','dialog');botTemplates.setAttribute('aria-modal','true');botTemplates.setAttribute('aria-label','Template tim bot');
botTemplates.innerHTML='<form id="botTemplatesForm"><h3>Template tim bot</h3><p class="hint">Pilih spesialis yang dibutuhkan. Bot yang sudah ada tidak ditimpa; tidak menambahkan skill atau ingatan.</p><div id="botTemplateItems" class="checks"></div><div class="row"><button class="btn pri">Tambahkan pilihan</button><button type="button" class="btn" id="closeBotTemplates">Batal</button></div></form>';document.body.append(botTemplates);
templatesButton.onclick=async()=>{try{const data=await api('/api/bot-templates');document.getElementById('botTemplateItems').innerHTML=data.items.map(b=>`<label><input type="checkbox" value="${esc(b.id)}" ${b.installed?'disabled':''}><span><b>${esc(b.name)}${b.installed?' · tersedia':''}</b><small class="hint">${esc(templateDescriptions[b.id]||b.persona.slice(0,90))}</small></span></label>`).join('');botTemplates.classList.remove('hidden');botTemplates.querySelector('input:not(:disabled),button').focus()}catch(e){sayError(e)}};
function closeBotTemplateModal(){botTemplates.classList.add('hidden');templatesButton.focus()}
document.getElementById('closeBotTemplates').onclick=closeBotTemplateModal;
botTemplates.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closeBotTemplateModal()}if(e.key==='Tab'){const items=Array.from(botTemplates.querySelectorAll('button,input')).filter(n=>!n.disabled);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
document.getElementById('botTemplatesForm').onsubmit=async e=>{e.preventDefault();try{const ids=Array.from(botTemplates.querySelectorAll('input:checked')).map(i=>i.value);const data=await api('/api/bot-templates',{method:'POST',body:{ids}});botTemplates.classList.add('hidden');await loadBots();toast(data.added.length+' template bot ditambahkan.')}catch(e){sayError(e)}};
const hostPanel=document.createElement('section');hostPanel.className='group compact-section';hostPanel.innerHTML='<h4>RAM & swap VPS</h4><div class="group-b"><p class="hint" id="hostResourceInfo">Membaca hardware…</p><label>Tambahkan swap<select class="inp" id="hostSwap"><option value="0">Pertahankan tanpa perubahan</option><option value="2">2 GB</option><option value="4">4 GB</option><option value="8">8 GB</option></select></label><button type="button" class="btn" id="hostSwapSave">Gunakan pilihan swap</button><p class="hint" id="hostResourceStatus" role="status"></p></div>';document.getElementById('setForm').append(hostPanel);
let hostPoll=null;
async function loadHostSetup(){
 clearTimeout(hostPoll);if(document.hidden)return;
 try{const s=await api('/api/host-setup');hostPanel.classList.toggle('hidden',!s.managed);$('#setupSwapRow').classList.toggle('hidden',!s.managed);const recommendation=s.recommended_swap_gb?`Rekomendasi: swap ${s.recommended_swap_gb} GB.`:s.swap_mb?'Swap sudah ada; tidak diubah.':'Tidak perlu menambah swap.';const note=`RAM ${(s.ram_mb/1024).toFixed(1)} GB · swap ${(s.swap_mb/1024).toFixed(1)} GB. ${recommendation} Swap memakai disk, lebih lambat dari RAM, dan tidak menaikkan batas container.`;$('#setupSwapHint').textContent=s.managed?note:'Swap dikelola oleh sistem operasi. Windows menggunakan virtual memory sistem.';$('#hostResourceInfo').textContent=note;$('#hostResourceStatus').textContent=s.pending?'Menunggu supervisor saat aplikasi senggang…':s.result.message||'';$('#hostSwapSave').disabled=s.pending;if(s.pending)hostPoll=setTimeout(loadHostSetup,4000)}catch(e){$('#hostResourceStatus').textContent='Menunggu aplikasi selesai restart…';hostPoll=setTimeout(loadHostSetup,4000)}
}
document.getElementById('hostSwapSave').onclick=async()=>{const size=Number($('#hostSwap').value);if(!size)return toast('Swap tetap dipertahankan.');if(!await uiConfirm(`Tambahkan swap ${size} GB di disk VPS? Swap yang sudah tersedia tidak akan diubah.`))return;try{await api('/api/host-setup',{method:'POST',body:{swap_gb:size}});await loadHostSetup();toast('Permintaan swap dikirim ke supervisor.')}catch(e){sayError(e)}};
async function prepareHarnessMemory(id){if(!await uiConfirm('Siapkan batas RAM container 2 GB untuk CLI asli? Aplikasi akan restart saat senggang, lalu mencoba pemasangan kembali. Data dan model lama dipertahankan.'))return;try{await api('/api/host-setup',{method:'POST',body:{harness_memory:true,retry:id}});await loadHostSetup();await loadHarnesses();toast('Supervisor menyiapkan container. Ini tidak mengunduh bobot model.')}catch(e){sayError(e)}}
const beforeHostSettings=loadSettings;loadSettings=async function(){await beforeHostSettings();await loadHostSetup()};
document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTimeout(hostPoll);else loadHostSetup()});loadHostSetup();if(window.refreshDesignControls)refreshDesignControls();
