const socialGuides={threads:'Buat aplikasi Threads di Meta for Developers, isi Threads App ID/secret dan callback HTTPS. Akses awal: profil dan posting sendiri.',instagram:'Gunakan akun Instagram Business/Creator dan aplikasi Instagram Login. Callback HTTPS harus terdaftar. App ID Instagram dapat berbeda dari App ID Facebook.',meta_ads:'Gunakan aplikasi Meta dengan ads_read untuk melihat akun/campaign. Untuk perubahan iklan, tambahkan MCP yang mendukung operasi tersebut dan tinjau izin tindakannya.',youtube:'Aktifkan YouTube Data API di Google Cloud, buat OAuth Client dan daftarkan callback. Akses awal hanya baca kanal. Upload video dapat memakai MCP dengan izin yang sesuai.'};
let socialFingerprint='',socialLoginProvider=null,socialAccounts=[];
function selectSocial(provider){$('#socialProvider').value=provider;const c=socialAccounts.find(x=>x.id===provider)||{};$('#socialClientId').value=c.client_id||'';$('#socialRedirect').value=c.redirect_uri||location.origin+'/oauth/callback';$('#socialWrite').checked=!!c.write_requested;['socialClientSecret','socialToken','socialCallback'].forEach(id=>$('#'+id).value='');socialGuide()}
async function loadSocial(){const d=await api('/api/social'),fingerprint=JSON.stringify(d);socialAccounts=d.connections;if(fingerprint!==socialFingerprint){socialFingerprint=fingerprint;$('#socialCards').innerHTML=d.connections.map(c=>`<article class="social-card"><b>${esc(c.name)}</b><span class="pill">${c.ready?'Akses baca terverifikasi':c.credential_found?'Perlu diuji':'Belum tersambung'}</span><p>${esc(c.account||c.note)}</p><div class="row"><button type="button" class="btn sm" data-social-connect="${c.id}">${c.configured?'Kelola':'Hubungkan'}</button><a class="btn sm" href="${esc(c.docs)}" target="_blank" rel="noopener">Panduan resmi</a></div></article>`).join('');$$('[data-social-connect]').forEach(b=>b.onclick=()=>{selectSocial(b.dataset.socialConnect);$('#socialConnectPanel').open=true;socialGuide();$('#socialConnectPanel').scrollIntoView({block:'nearest'})})}socialGuide()}
function socialGuide(){$('#socialGuide').textContent=socialGuides[$('#socialProvider').value]}
$('#socialProvider').onchange=()=>{selectSocial($('#socialProvider').value);$('#socialCallbackBox').classList.add('hidden')};
$('#refreshSocial').onclick=()=>loadSocial().catch(sayError);
async function socialSave(){const provider=$('#socialProvider').value;await api('/api/social/'+provider,{method:'POST',body:{action:'save',client_id:$('#socialClientId').value,client_secret:$('#socialClientSecret').value,redirect_uri:$('#socialRedirect').value,access_token:$('#socialToken').value,write_requested:$('#socialWrite').checked}});$('#socialClientSecret').value='';$('#socialToken').value='';return provider}
$('#socialForm').onsubmit=async e=>{e.preventDefault();try{await socialSave();$('#socialResult').textContent='Konfigurasi disimpan. Lanjutkan login atau uji akses baca.';await loadSocial()}catch(e){$('#socialResult').textContent=e.message}};
$('#socialStart').onclick=async()=>{try{const provider=await socialSave(),d=await api('/api/social/'+provider,{method:'POST',body:{action:'start'}});socialLoginProvider=provider;$('#socialLoginLink').href=d.url;$('#socialCallbackBox').classList.remove('hidden');$('#socialResult').textContent='Login siap dibuka. Callback terdaftar: '+d.callback}catch(e){$('#socialResult').textContent=e.message}};
$('#socialVerify').onclick=async()=>{try{await socialSave();const d=await api('/api/social/'+$('#socialProvider').value,{method:'POST',body:{action:'verify'}});$('#socialResult').textContent='Akses baca berhasil: '+d.account;await loadSocial()}catch(e){$('#socialResult').textContent='Belum tersambung: '+e.message;await loadSocial()}};
$('#socialFinish').onclick=async()=>{try{if(!socialLoginProvider)throw Error('Mulai login dahulu.');const d=await api('/api/social/'+socialLoginProvider,{method:'POST',body:{action:'finish',callback:$('#socialCallback').value}});$('#socialCallback').value='';$('#socialCallbackBox').classList.add('hidden');$('#socialResult').textContent='Akses baca terverifikasi: '+d.account;await loadSocial()}catch(e){$('#socialResult').textContent=e.message}};
$('#setupDone').onclick=async()=>{try{const result=await api('/api/setup',{method:'POST',body:{profile:$('#setupProfile').value,harness:$('#setupHarness').value,full_access:$('#setupFullAccess').checked}});$('#setupGuide').classList.add('hidden');await refreshBots();go('chat');toast(result.mcp_errors?.length?'Setup disimpan; MCP belum tersambung. Periksa tab MCP.':'Setup disimpan. Koneksi bisa ditambah kapan saja.')}catch(e){sayError(e)}};
